services:
  - type: web
    name: satellite-srm-backend
    env: python
    plan: free
    rootDir: satellite-srm-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
